version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 6;li*4+MRy@b0wcr=R0o:Qwg3=C7l2/4

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-RESTAPI
    restart: on-failure
      # command: >
    ports:
      - "8000:8080"
    environment:
        SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:mysql://database:3306/Spring_API?createDatabaseIfNotExist=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "6;li*4+MRy@b0wcr=R0o:Qwg3=C7l2/4",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.hibernate.dialect" : "org.hibernate.dialect.MYSQL5InnoDBDialect"
          }'
    depends_on:
      - db



  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"